version: "3.9"

services:
  zapchastimira_main_db:
    image: postgres:16
    container_name: zapchastimira_main_db
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - zapchastimira_main_db_data:/var/lib/postgresql/data

  zapchastimira_main_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zapchastimira_main_bot
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}

    command: ["python", "-m","zapchastimira.interface.telegram"]

volumes:
  zapchastimira_main_db_data:
    driver: local
