version: "3.9"

services:
  zapchastimira_main_db:
    image: postgres:16
    container_name: zapchastimira_main_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - zapchastimira_main_db_data:/var/lib/postgresql/data


volumes:
  zapchastimira_main_db_data:
    driver: local