"""Add contact table

Revision ID: 491b05a5f3ea
Revises: 8ef7e5f0f8ce
Create Date: 2025-01-28 14:21:26.934761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '491b05a5f3ea'
down_revision: Union[str, None] = '8ef7e5f0f8ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('contact_id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('contact_id'),
    sa.UniqueConstraint('phone')
    )
    op.drop_index('idx_parts_search_vector', table_name='parts', postgresql_using='gin')
    op.drop_index('idx_products_search_vector', table_name='products', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_products_search_vector', 'products', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('idx_parts_search_vector', 'parts', ['search_vector'], unique=False, postgresql_using='gin')
    op.drop_table('contacts')
    # ### end Alembic commands ###
