"""add column base category id

Revision ID: 78427d67883c
Revises: 564d5281d055
Create Date: 2025-01-22 12:41:37.618890

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "78427d67883c"
down_revision: Union[str, None] = "564d5281d055"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("part_category", sa.Column("base_categoty_id", sa.String(), nullable=False))
    op.create_foreign_key(None, "part_category", "categories", ["base_categoty_id"], ["category_id"])
    op.add_column("product_category", sa.Column("base_categoty_id", sa.String(), nullable=False))
    op.create_foreign_key(None, "product_category", "categories", ["base_categoty_id"], ["category_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "product_category", type_="foreignkey")
    op.drop_column("product_category", "base_categoty_id")
    op.drop_constraint(None, "part_category", type_="foreignkey")
    op.drop_column("part_category", "base_categoty_id")
    # ### end Alembic commands ###
